name: earthy
channels:
  - conda-forge
  - defaults
dependencies:
  - compas
  - ipywidgets
  - jupyter
  - meshplot
  - pandas
  - pip
  - python=3.8.5
  - pyvista
  - pip:
      - ipyvtklink
      - itkwidgets
      - specklepy
      - git+https://github.com/shervinazadi/topoGenesis.git